<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.547">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Milan Fathimah Az Zahra Sandy">
<meta name="dcterms.date" content="2024-01-23">

<title>Pengaruh Inflasi dan Pertumbuhan Ekonomi Terhadap Tingkat Pengangguran Terbuka (TPT) di Jawa Barat</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Inflasi dan Pertumbuhan Ekonomi Terhadap Tingkat Pengangguran Terbuka (TPT) di Jawa Barat</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Milan Fathimah Az Zahra Sandy </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 23, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
<div style="text-align: justify">
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar Belakang</h3>
<p>Tingkat Pengangguran Terbuka atau yang sering disebut dengan TPT merupakan persentase dari jumlah pengangguran terhadap jumlah angkatan kerja. Menurut Mantra (2009) pengangguran adalah bagian dari angkatan kerja yang sekarang ini tidak bekerja dan sedang aktif mencari pekerjaan. Konsep ini sering diartikan sebagai keadaan pengangguran terbuka. Pengangguran terbuka adalah persentase penduduk yang mencari pekerjaan, yang mempersiapkan usaha, yang tidak mencari pekerjaan karena merasa tidak mungkin mendapatkan pekerjaan, yang sudah mempunyai pekerjaan tetapi belum mulai bekerja dari sejumlah angkatan kerja yang ada (Sukirno, 2000).</p>
<p>Salah satu faktor penyebab ada nya pengangguran terbuka yaitu inflasi dan pertumbuhan ekonomi. Inflasi yang tinggi akan menekan angka pengangguran yang semakin tinggi. Lalu untuk pertumbuhan ekonomi sendiri jika ia mengalami penurunan maka angka TPT akan mengalami kenaikan, begitu pula sebaliknya.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang Lingkup</h3>
<p>Pada penelitian ini, penulis mengambil ruang lingkup yang sesuai dengan variabel yang dijelaskan. Penulis menggunakan 3 variabel, yaitu Inflasi dan Pertumbuhan Ekonomi Terhadap Tingkat Pengangguran Terbuka (TPT) di Jawa Barat. Data yang digunakan bersifat time series dalam kurun waktu 2017-2022.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan Masalah</h3>
<ol type="1">
<li>Apakah inflasi dan pertumbuhan ekonomi berpengaruh signifikan terhadap TPT di Jawa Barat?</li>
<li>Apakah terdapat hubungan signifikan antara inflasi dan TPT di Jawa Barat?</li>
<li>Apakah pertumbuhan ekonomi berkontribusi terhadap penurunan TPT di Jawa Barat?</li>
<li>Bagaimana dampak jangka panjang dan jangka pendek dari inflasi dan pertumbuhan ekonomi terhadap TPT di Jawa Barat?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan Manfaat Penelitian</h3>
<p>Penelitian ini bertujuan untuk mengetahui pengaruh dari inflasi dan pertumbuhan ekonomi terhadap Tingkat Pengangguran Terbuka (TPT) di Jawa Barat pada tahun terkait (2017-2022).</p>
<p>Manfaat penelitian ini agar masyarakat paham akan adanya pengaruh dari inflasi dan pertumbuhan ekonomi terhadap Tingkat Pengangguran Terbuka (TPT) di Jawa Barat pada tahun terkait (2017-2022).</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'corrplot'</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'car'</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'dplyr'</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'broom'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'ggplot2'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi Pustaka</h2>
<p><strong>1. Inflasi</strong></p>
<p>Inflasi didefinisikan dengan banyak ragam yang berbeda, tetapi semua definisi itu mencakup pokok-pokok yang sama. Samuelson (2001) memberikan definisi bahwa inflasi sebagai suatu keadaan dimana terjadi kenaikan tingkat harga umum, baik barang-barang, jasa-jasa maupun faktor-faktor produksi. Adapula pengertian inflasi menurut Gilarso (2013:200) adalah kenaikan harga umum, yang bersumber pada terganggunya keseimbangan antara arus uang dan arus barang.</p>
<p><strong>2. Pertumbuhan Ekonomi</strong></p>
<p>Pertumbuhan ekonomi adalah sebuah proses dari perubahan kondisi perekonomian yang terjadi di suatu negara secara berkesinambungan untuk menuju keadaan yang dinilai lebih baik selama jangka waktu tertentu. Pertumbuhan ekonomi merupakan upaya peningkatan kapasitas produksi untuk mencapai penambahan output, yang diukur menggunakan Produk Domestik Bruto (PDB) maupun menggunakan Produk Domestik Regional Bruto (PDRB) dalam suatu wilayah. (Rahardjo, 2013). Simon Kuznets (dalam Arsyad, 2010) menyatakan bahwa pertumbuhan ekonomi merupakan kenaikan kapasitas jangka panjang dari negara yang bersangkutan untuk menyediakan berbagai barang ekonomi kepada penduduknya. Kenaikan kapasitas tersebut dimungkinkan oleh adanya kemajuan atau penyesuaian-penyesuaian teknologi, institusional dan ideologi terhadap berbagai keadaan yang ada.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode Penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Data dibawah ini merupakan data Inflasi, Pertumbuhan Ekonomi, dan TPT di Provinsi Jawa Barat (dalam bentuk persen).</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Tahun</th>
<th style="text-align: center;">Inflasi</th>
<th style="text-align: center;">Pertumbuhan Ekonomi</th>
<th style="text-align: center;">TPT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2017</td>
<td style="text-align: center;">3,63</td>
<td style="text-align: center;">5,29</td>
<td style="text-align: center;">8,22</td>
</tr>
<tr class="even">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">3,54</td>
<td style="text-align: center;">5,64</td>
<td style="text-align: center;">8,23</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">3,42</td>
<td style="text-align: center;">5,07</td>
<td style="text-align: center;">8,04</td>
</tr>
<tr class="even">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">1,99</td>
<td style="text-align: center;">2,44</td>
<td style="text-align: center;">10,46</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">1,74</td>
<td style="text-align: center;">3,74</td>
<td style="text-align: center;">9,82</td>
</tr>
<tr class="even">
<td style="text-align: center;">2022</td>
<td style="text-align: center;">5,75</td>
<td style="text-align: center;">5,45</td>
<td style="text-align: center;">8,31</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk time series (2017-2022). Data yang digunakan yaitu data yang telah diolah dari Badan Pusat Statistik Jawa Barat.</p>
<p>Baca data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/UAS METOPEL/BOOK5.xlsx"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Tahun         Inflasi      PertumbuhanEkonomi      TPT        
 Min.   :2017   Min.   :1.740   Min.   :2.440      Min.   : 8.040  
 1st Qu.:2018   1st Qu.:2.348   1st Qu.:4.072      1st Qu.: 8.223  
 Median :2020   Median :3.480   Median :5.180      Median : 8.270  
 Mean   :2020   Mean   :3.345   Mean   :4.605      Mean   : 8.847  
 3rd Qu.:2021   3rd Qu.:3.607   3rd Qu.:5.410      3rd Qu.: 9.443  
 Max.   :2022   Max.   :5.750   Max.   :5.640      Max.   :10.460  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [6 × 4] (S3: tbl_df/tbl/data.frame)
 $ Tahun             : num [1:6] 2017 2018 2019 2020 2021 ...
 $ Inflasi           : num [1:6] 3.63 3.54 3.42 1.99 1.74 5.75
 $ PertumbuhanEkonomi: num [1:6] 5.29 5.64 5.07 2.44 3.74 5.45
 $ TPT               : num [1:6] 8.22 8.23 8.04 10.46 9.82 ...</code></pre>
</div>
</div>
<p><strong>Plot pengaruh error terhadap Inflasi</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/PLOT ERROR INFLASI/BOOK1.xlsx"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>dat)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>x,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"Inflasi"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Plot pengaruh error terhadap TPT</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/PLOT ERROR INFLASI/BOOK1.xlsx"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>dat)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>y,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"TPT"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Plot Hubungan Antara Inflasi, Pertumbuhan Ekonomi dan TPT</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Rplotggp.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode Analisis</h3>
<p>Metode analisis yang dipilih adalah Regresi Multivariat dengan 2 variabel independen. Penelitian ini bertujuan untuk mengetahui pengaruh dari inflasi (X1) dan pertumbuhan ekonomi (X2) terhadap Tingkat Pengangguran Terbuka (Y) di Jawa Barat pada tahun terkait (2017-2022). Spesifikasinya adalah:</p>
<p><span class="math display">\[
Y=\beta_0 + \beta_1 X_1+\ \beta_2 X_2+\ \mu_t
\]</span> Di mana <span class="math inline">\(Y\)</span> adalah TPT Jawa Barat, <span class="math inline">\(X1\)</span> adalah inflasi Jawa Barat, dan <span class="math inline">\(X2\)</span> adalah pertumbuhan ekonomi Jawa Barat.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan Masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">Std.Error</th>
<th style="text-align: center;">t-value</th>
<th style="text-align: center;">Prob (.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">12.46913</td>
<td style="text-align: center;">0.58539</td>
<td style="text-align: center;">21.300</td>
<td style="text-align: center;">0.000226</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inflasi</td>
<td style="text-align: center;">-0.01116</td>
<td style="text-align: center;">0.16125</td>
<td style="text-align: center;">-0.069</td>
<td style="text-align: center;">0.949199</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pertumbuhan Ekonomi</td>
<td style="text-align: center;">-0.77853</td>
<td style="text-align: center;">0.18424</td>
<td style="text-align: center;">-4.226</td>
<td style="text-align: center;">0.024239</td>
</tr>
<tr class="even">
<td style="text-align: left;">R Squared</td>
<td style="text-align: center;">0.9333</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adjusted R-Squared</td>
<td style="text-align: center;">0.8889</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">F-Statistic</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prob(F-Statistic)</td>
<td style="text-align: center;">0.01721</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Hasil regresi yang didapatkan kemudian dimasukkan ke dalam rumus persamaan</p>
<p><span class="math display">\[
Y=12.469 + (-0.011 X1) + (-0.778 X2)
\]</span></p>
<p>Inflasi berperan dalam penurunan TPT dikarenakan variabel X1 yang negatif. Begitu pula dengan Pertumbuhan Ekonomi yang berperan dalam penurunan TPT. Jika diasumsikan inflasi naik 1 satuan, maka TPT di Jawa Barat akan mengalami penurunan sebesar 0.011. Kemudian jika pertumbuhan ekonomi diasumsikan naik 1 satuan, maka TPT di Jawa Barat akan mengalami penurunan sebesar 0.778.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis Masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/UAS METOPEL/BOOK5.xlsx"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(TPT<span class="sc">~</span>Inflasi<span class="sc">+</span>PertumbuhanEkonomi,<span class="at">data=</span>dat)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TPT ~ Inflasi + PertumbuhanEkonomi, data = dat)

Residuals:
       1        2        3        4        5        6 
-0.09019  0.19129 -0.44381 -0.08731  0.28200  0.14802 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        12.46913    0.58539  21.300 0.000226 ***
Inflasi            -0.01116    0.16125  -0.069 0.949199    
PertumbuhanEkonomi -0.77853    0.18424  -4.226 0.024239 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3419 on 3 degrees of freedom
Multiple R-squared:  0.9333,    Adjusted R-squared:  0.8889 
F-statistic:    21 on 2 and 3 DF,  p-value: 0.01721</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Membuat plot matriks korelasi</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/UAS METOPEL/BOOK5.xlsx"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(dat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Membuat plot sisa parsial</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'car'</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/UAS METOPEL/BOOK5.xlsx"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(TPT <span class="sc">~</span> Inflasi <span class="sc">+</span> PertumbuhanEkonomi, <span class="at">data =</span> dat)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">crPlots</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<section id="kesimpulan-regresi" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="kesimpulan-regresi"><span class="header-section-number">5.1</span> Kesimpulan Regresi</h3>
<p>Dari hasil regresi multivariat di atas, maka dapat disimpulkan antara lain:</p>
<ol type="1">
<li>a sebesar 12.46913 merupakan konstanta atau keadaan saat variabel TPT belum dipengaruhi oleh variabel lainnya, yaitu variabel inflasi (X1) dan pertumbuhan ekonomi (X2). Jika variabel independen tidak ada, maka variabel TPT di Jawa Barat tidak akan mengalami perubahan.</li>
<li>Nilai koefisien regresi inflasi (X1) bernilai negatif sebesar -0.011 dapat diasumsikan bahwa jika variabel inflasi meningkat 1 satuan, maka TPT di Jawa Barat akan menurun sebesar 0.011.</li>
<li>Nilai koefisien regresi pertumbuhan ekonomi (X2) bernilai negatif sebesar -0.788 dapat diasumsikan bahwa jika variabel pertumbuhan ekonomi meningkat 1 satuan, maka TPT di Jawa Barat akan menurun sebesar 0.778.</li>
</ol>
</section>
<section id="uji-hipotesis" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="uji-hipotesis"><span class="header-section-number">5.2</span> Uji Hipotesis</h3>
<p>Dari hasil regresi multivariat di atas, maka dapat disimpulkan uji hipotesis yang diperoleh antara lain:</p>
<ol type="1">
<li>Nilai sig variabel inflasi (X1) sebesar 0.94 (&gt;0.05), maka dapat disimpulkan bahwa variabel inflasi (X1) tidak berpengaruh signifikan terhadap variabel TPT di Jawa Barat (Y).</li>
<li>Nilai sig variabel pertumbuhan ekonomi (X2) sebesar 0.02 (&lt;0.05), maka dapat disimpulkan bahwa variabel pertumbuhan ekonomi (X2) berpengaruh signifikan terhadap variabel TPT di Jawa Barat (Y).</li>
</ol>
</section>
<section id="koefisien-determinasi" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="koefisien-determinasi"><span class="header-section-number">5.3</span> Koefisien Determinasi</h3>
<p>Berdasarkan hasil regresi yang didapatkan, diketahui bahwa nilai koefisien determinasi sebesar 93.33% yang artinya inflasi dan pertumbuhan ekonomi Jawa Barat memberikan kontribusi sebesar 93.33% terhadap TPT di Jawa Barat. Sedangkan sisanya sebesar 6.67% disebabkan oleh faktor lain yang tidak diteliti oleh penulis.</p>
</section>
<section id="kesimpulan-akhir" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="kesimpulan-akhir"><span class="header-section-number">5.4</span> Kesimpulan Akhir</h3>
<p>Berdasarkan rumusan masalah yang sudah diberitahukan. Maka dapat disimpulkan sebagai berikut:</p>
<ol type="1">
<li>Untuk inflasi sendiri tidak berpengaruh signifikan terhadap TPT di Jawa Barat karena memiliki nilai signifikansi 0.94 (&gt;0.05). Sedangkan pertumbuhan ekonomi berpengaruh signifikan terhadap TPT di Jawa Barat karena memiliki nilai signifikansi 0.02 (&lt;0.05).</li>
<li>Inflasi tidak berpengaruh signifikan terhadap TPT di Jawa Barat.</li>
<li>Pertumbuhan ekonomi berkontribusi terhadap penurunan TPT di Jawa Barat sebesar 0.778.</li>
<li>Dampak jangka pendek dan jangka panjang untuk inflasi dan pertumbuhan ekonomi sudah pasti akan mempengaruhi TPT yang di mana ketika inflasi naik, maka angka TPT di Jawa Barat akan semakin meningkat karena perusahaan akan mengurangi output dan mengambil kebijakan dengan mengurangi tenaga kerja. Sehingga, akan ada PHK. Terutama jika hiperinflasi pasti akan terjadi PHK massal. Kemudian untuk pertumbuhan ekonomi, ketika naik maka angka TPT di Jawa Barat akan mengalami penurunan. Karena pertumbuhan ekonomi yang naik menandakan kesejahteraan masyarakat di daerah tersebut. Semakin tinggi pertumbuhan ekonomi, maka kesejahteraan masyarakat akan semakin baik sehingga angka TPT akan menurun.</li>
</ol>
</section>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Marini, L., &amp; Putri, N. T. (2020). Peluang Terjadinya Pengangguran Di Provinsi Bengkulu : Seberapa Besar?. Convergence: The Journal of Economic Development, 1(2), 70–83. https://doi.org/10.33369/convergence-jep.v1i2.10900.</p>
<p>Suparmono, &amp; Puteri, N. A. (2018). Analisis Pengangguran Terbuka Di Provinsi Jawa Timur Tahun 2013-2016. Yogyakarta: Universitas Islam Indonesia, 20–55.</p>
<p>Milasari, A. S. (2020). Pengaruh Perubahan Nilai Tukar Terhadap Harga Barang Impor Dan Inflasi Dalam Negeri Di Beberapa Negara Industri. Jurnal Ekonomi, 14–35.</p>
<p>Sulistiawati, R. (2012). Pengaruh Investasi terhadap Pertumbuhan Ekonomi dan Penyerapan Tenaga Kerja Serta Kesejahteraan Masyarakat di Provinsi di Indonesia. Jurnal Ekonomi Bisnis Dan Kewirausahaan, 3(1), 29–50. DOI :10.26418/jebik.v3i1.9888.</p>
<p>Badan Pusat Statistik. Tingkat Pengangguran Terbuka Kabupaten/Kota (Persen), 2017-2022. Badan Pusat Statistik Provinsi Jawa Barat, accessed: 02-01-2024.</p>
<p>Bintang, Y. S., &amp; Prana, R. R. (2020). Pengaruh Inflasi terhadap Tingkat Pengangguran Terbuka di Kota Medan Sri. Jurnal Studi Manajemen, 5–24.</p>
</section>
</div>
<p>.</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>